name: Run python script hourly

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: |
            python hello.py

    - name: Upload logs.txt
      if: success()
      uses: actions/upload-artifact@v4
      with:
          name: logs
          path: logs.txt
